QLXeBusPhuongTrang_65134257/Controllers/LichChay_65134257Controller.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using QLXeBusPhuongTrang_65134257.Models;

namespace QLXeBusPhuongTrang_65134257.Controllers
{
    public class LichChay_65134257Controller : Controller
    {
        private QLXeBusPhuongTrang_65134257Entities db = new QLXeBusPhuongTrang_65134257Entities();

        // GET: LichChay_65134257
        public ActionResult Index()
        {
            var lichChays = db.LichChays.Include(l => l.TaiXe).Include(l => l.Tuyen).Include(l => l.Xe);
            return View(lichChays.ToList());
        }

        // GET: LichChay_65134257/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LichChay lichChay = db.LichChays.Find(id);
            if (lichChay == null)
            {
                return HttpNotFound();
            }
            return View(lichChay);
        }

        // GET: LichChay_65134257/Create
        public ActionResult Create()
        {
            ViewBag.MaTaiXe = new SelectList(db.TaiXes, "MaTaiXe", "HoTen");
            ViewBag.MaTuyen = new SelectList(db.Tuyens, "MaTuyen", "TenTuyen");
            ViewBag.MaXe = new SelectList(db.Xes, "MaXe", "BienSo");
            return View();
        }

        // POST: LichChay_65134257/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaLichChay,MaTuyen,MaXe,MaTaiXe,GioKhoiHanh,GioDen,TrangThai")] LichChay lichChay)
        {
            if (ModelState.IsValid)
            {
                db.LichChays.Add(lichChay);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.MaTaiXe = new SelectList(db.TaiXes, "MaTaiXe", "HoTen", lichChay.MaTaiXe);
            ViewBag.MaTuyen = new SelectList(db.Tuyens, "MaTuyen", "TenTuyen", lichChay.MaTuyen);
            ViewBag.MaXe = new SelectList(db.Xes, "MaXe", "BienSo", lichChay.MaXe);
            return View(lichChay);
        }

        // GET: LichChay_65134257/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LichChay lichChay = db.LichChays.Find(id);
            if (lichChay == null)
            {
                return HttpNotFound();
            }
            ViewBag.MaTaiXe = new SelectList(db.TaiXes, "MaTaiXe", "HoTen", lichChay.MaTaiXe);
            ViewBag.MaTuyen = new SelectList(db.Tuyens, "MaTuyen", "TenTuyen", lichChay.MaTuyen);
            ViewBag.MaXe = new SelectList(db.Xes, "MaXe", "BienSo", lichChay.MaXe);
            return View(lichChay);
        }

        // POST: LichChay_65134257/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaLichChay,MaTuyen,MaXe,MaTaiXe,GioKhoiHanh,GioDen,TrangThai")] LichChay lichChay)
        {
            if (ModelState.IsValid)
            {
                db.Entry(lichChay).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MaTaiXe = new SelectList(db.TaiXes, "MaTaiXe", "HoTen", lichChay.MaTaiXe);
            ViewBag.MaTuyen = new SelectList(db.Tuyens, "MaTuyen", "TenTuyen", lichChay.MaTuyen);
            ViewBag.MaXe = new SelectList(db.Xes, "MaXe", "BienSo", lichChay.MaXe);
            return View(lichChay);
        }

        // GET: LichChay_65134257/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LichChay lichChay = db.LichChays.Find(id);
            if (lichChay == null)
            {
                return HttpNotFound();
            }
            return View(lichChay);
        }

        // POST: LichChay_65134257/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                LichChay lichChay = db.LichChays.Find(id);
                db.LichChays.Remove(lichChay);
                db.SaveChanges();

                // THÊM DÒNG NÀY: Lưu thông báo thành công
                TempData["Success"] = "Đã xóa lịch chạy thành công!";

                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                // Lưu thông báo lỗi
                TempData["Error"] = "Không thể xóa lịch chạy này vì đã có dữ liệu chuyến xe liên quan!";
                return RedirectToAction("Index");
            }
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

QLXeBusPhuongTrang_65134257/Controllers/Tuyen_65134257Controller.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using QLXeBusPhuongTrang_65134257.Models;

namespace QLXeBusPhuongTrang_65134257.Controllers
{
    public class Tuyen_65134257Controller : Controller
    {
        private QLXeBusPhuongTrang_65134257Entities db = new QLXeBusPhuongTrang_65134257Entities();

        // GET: Tuyen_65134257
        public ActionResult Index(int? BenDauId, int? BenCuoiId)
        {
            // 1. Chuẩn bị Dropdown List cho Bến Xe
            // Dùng SelectList để dễ dàng liên kết trong View
            ViewBag.BenDauId = new SelectList(db.BenXes.ToList(), "MaBen", "TenBen", BenDauId);
            ViewBag.BenCuoiId = new SelectList(db.BenXes.ToList(), "MaBen", "TenBen", BenCuoiId);

            // 2. Bắt đầu truy vấn
            IQueryable<Tuyen> tuyens = db.Tuyens
                                        .Include(t => t.BenXe) // Bến Đi
                                        .Include(t => t.BenXe1); // Bến Đến (BenCuoi)

            // 3. Xử lý Lọc theo Bến Đi (BenDau)
            if (BenDauId.HasValue)
            {
                tuyens = tuyens.Where(t => t.BenDau == BenDauId.Value);
            }

            // 4. Xử lý Lọc theo Bến Đến (BenCuoi)
            if (BenCuoiId.HasValue)
            {
                tuyens = tuyens.Where(t => t.BenCuoi == BenCuoiId.Value);
            }

            // Trả về danh sách đã lọc (hoặc toàn bộ nếu không có lọc)
            return View(tuyens.ToList());
        }

        // GET: Tuyen_65134257/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tuyen tuyen = db.Tuyens.Find(id);
            if (tuyen == null)
            {
                return HttpNotFound();
            }
            return View(tuyen);
        }

        // GET: Tuyen_65134257/Create
        public ActionResult Create()
        {
            ViewBag.BenCuoi = new SelectList(db.BenXes, "MaBen", "TenBen");
            ViewBag.BenDau = new SelectList(db.BenXes, "MaBen", "TenBen");
            return View();
        }

        // POST: Tuyen_65134257/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaTuyen,TenTuyen,BenDau,BenCuoi,QuangDuongKm")] Tuyen tuyen)
        {
            if (ModelState.IsValid)
            {
                db.Tuyens.Add(tuyen);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.BenCuoi = new SelectList(db.BenXes, "MaBen", "TenBen", tuyen.BenCuoi);
            ViewBag.BenDau = new SelectList(db.BenXes, "MaBen", "TenBen", tuyen.BenDau);
            return View(tuyen);
        }

        // GET: Tuyen_65134257/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tuyen tuyen = db.Tuyens.Find(id);
            if (tuyen == null)
            {
                return HttpNotFound();
            }
            ViewBag.BenCuoi = new SelectList(db.BenXes, "MaBen", "TenBen", tuyen.BenCuoi);
            ViewBag.BenDau = new SelectList(db.BenXes, "MaBen", "TenBen", tuyen.BenDau);
            return View(tuyen);
        }

        // POST: Tuyen_65134257/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaTuyen,TenTuyen,BenDau,BenCuoi,QuangDuongKm")] Tuyen tuyen)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tuyen).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.BenCuoi = new SelectList(db.BenXes, "MaBen", "TenBen", tuyen.BenCuoi);
            ViewBag.BenDau = new SelectList(db.BenXes, "MaBen", "TenBen", tuyen.BenDau);
            return View(tuyen);
        }

        // GET: Tuyen_65134257/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tuyen tuyen = db.Tuyens.Find(id);
            if (tuyen == null)
            {
                return HttpNotFound();
            }
            return View(tuyen);
        }

        // POST: Tuyen_65134257/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                // 1. Tìm tuyến cần xóa
                Tuyen tuyen = db.Tuyens.Find(id);

                // 2. Xóa và lưu
                db.Tuyens.Remove(tuyen);
                db.SaveChanges();

                // 3. Thông báo thành công
                TempData["Success"] = "Đã xóa tuyến xe thành công!";
                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                // 4. Nếu lỗi (do Tuyến đang có Lịch Chạy sử dụng)
                TempData["Error"] = "Không thể xóa tuyến này vì đang có Lịch chạy hoặc dữ liệu liên quan!";
                return RedirectToAction("Index");
            }
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

QLXeBusPhuongTrang_65134257/Views/LichChay_65134257/Create.cshtml
@model QLXeBusPhuongTrang_65134257.Models.LichChay

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="container py-4">
    <div class="row justify-content-center">
        <div class="col-md-10 col-lg-8">
            <div class="card shadow-lg border-0 rounded-4">

                <div class="card-header bg-gradient-primary text-white py-3 rounded-top-4" style="background: linear-gradient(45deg, #0d6efd, #0a58ca);">
                    <h4 class="mb-0 text-center fw-bold"><i class="fas fa-calendar-plus me-2"></i> THÊM LỊCH CHẠY</h4>
                </div>

                <div class="card-body p-4 p-md-5">
                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()
                        @Html.ValidationSummary(true, "", new { @class = "alert alert-danger mb-4" })

                        <div class="mb-4">
                            @Html.LabelFor(model => model.MaTuyen, "Tuyến Xe", htmlAttributes: new { @class = "form-label fw-bold text-secondary" })
                            <div class="input-group">
                                <span class="input-group-text bg-light"><i class="fas fa-route text-primary"></i></span>
                                @Html.DropDownList("MaTuyen", null, htmlAttributes: new { @class = "form-select form-control-lg" })
                            </div>
                            @Html.ValidationMessageFor(model => model.MaTuyen, "", new { @class = "text-danger small ms-2" })
                        </div>

                        <div class="row">
                            <div class="col-md-6 mb-4">
                                @Html.LabelFor(model => model.MaXe, "Xe Chạy", htmlAttributes: new { @class = "form-label fw-bold text-secondary" })
                                <div class="input-group">
                                    <span class="input-group-text bg-light"><i class="fas fa-bus text-success"></i></span>
                                    @Html.DropDownList("MaXe", null, htmlAttributes: new { @class = "form-select" })
                                </div>
                                @Html.ValidationMessageFor(model => model.MaXe, "", new { @class = "text-danger small ms-2" })
                            </div>

                            <div class="col-md-6 mb-4">
                                @Html.LabelFor(model => model.MaTaiXe, "Tài Xế", htmlAttributes: new { @class = "form-label fw-bold text-secondary" })
                                <div class="input-group">
                                    <span class="input-group-text bg-light"><i class="fas fa-user-tie text-info"></i></span>
                                    @Html.DropDownList("MaTaiXe", null, htmlAttributes: new { @class = "form-select" })
                                </div>
                                @Html.ValidationMessageFor(model => model.MaTaiXe, "", new { @class = "text-danger small ms-2" })
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-6 mb-4">
                                @Html.LabelFor(model => model.GioKhoiHanh, "Giờ Khởi Hành", htmlAttributes: new { @class = "form-label fw-bold text-secondary" })
                                <div class="input-group">
                                    <span class="input-group-text bg-light"><i class="fas fa-clock text-warning"></i></span>
                                    @Html.EditorFor(model => model.GioKhoiHanh, new { htmlAttributes = new { @class = "form-control", type = "time" } })
                                </div>
                                @Html.ValidationMessageFor(model => model.GioKhoiHanh, "", new { @class = "text-danger small ms-2" })
                            </div>

                            <div class="col-md-6 mb-4">
                                @Html.LabelFor(model => model.GioDen, "Giờ Đến (Dự kiến)", htmlAttributes: new { @class = "form-label fw-bold text-secondary" })
                                <div class="input-group">
                                    <span class="input-group-text bg-light"><i class="fas fa-flag-checkered text-danger"></i></span>
                                    @Html.EditorFor(model => model.GioDen, new { htmlAttributes = new { @class = "form-control", type = "time" } })
                                </div>
                                @Html.ValidationMessageFor(model => model.GioDen, "", new { @class = "text-danger small ms-2" })
                            </div>
                        </div>

                        <div class="mb-4">
                            @Html.LabelFor(model => model.TrangThai, "Trạng Thái", htmlAttributes: new { @class = "form-label fw-bold text-secondary" })
                            <div class="input-group">
                                <span class="input-group-text bg-light"><i class="fas fa-info-circle text-secondary"></i></span>
                                @Html.EditorFor(model => model.TrangThai, new { htmlAttributes = new { @class = "form-control" } })
                            </div>
                            @Html.ValidationMessageFor(model => model.TrangThai, "", new { @class = "text-danger small ms-2" })
                        </div>

                        <div class="d-flex justify-content-center gap-3 mt-3">
                            <a href="@Url.Action("Index", "Tuyen_65134257")" class="btn btn-outline-secondary px-4 rounded-pill">
                                <i class="fas fa-arrow-left me-2"></i> Quay Lại
                            </a>
                            <button type="submit" class="btn btn-primary px-5 rounded-pill shadow-sm">
                                <i class="fas fa-save me-2"></i> Lưu Lịch Chạy
                            </button>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

<style>
    /* CSS Tùy chỉnh nhẹ */
    .form-control, .form-select, .input-group-text {
        border-color: #dee2e6;
        padding: 10px 15px;
    }

        .form-control:focus, .form-select:focus {
            border-color: #0d6efd;
            box-shadow: 0 0 0 0.25rem rgba(13, 110, 253, 0.15);
        }

    .input-group-text {
        background-color: #f8f9fa;
        border-right: none;
    }

    .form-control, .form-select {
        border-left: none;
    }

    /* Hiệu ứng hover cho card */
    .card {
        transition: transform 0.3s;
    }
</style>

QLXeBusPhuongTrang_65134257/Views/LichChay_65134257/Delete.cshtml
@model QLXeBusPhuongTrang_65134257.Models.LichChay

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>LichChay</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.GioKhoiHanh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GioKhoiHanh)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GioDen)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GioDen)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TrangThai)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TrangThai)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TaiXe.HoTen)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TaiXe.HoTen)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tuyen.TenTuyen)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tuyen.TenTuyen)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Xe.BienSo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Xe.BienSo)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

QLXeBusPhuongTrang_65134257/Views/LichChay_65134257/Details.cshtml
@model QLXeBusPhuongTrang_65134257.Models.LichChay

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Details</h2>

<div>
    <h4>LichChay</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.GioKhoiHanh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GioKhoiHanh)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GioDen)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GioDen)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TrangThai)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TrangThai)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TaiXe.HoTen)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TaiXe.HoTen)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tuyen.TenTuyen)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tuyen.TenTuyen)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Xe.BienSo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Xe.BienSo)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.MaLichChay }) |
    @Html.ActionLink("Back to List", "Index")
</p>

QLXeBusPhuongTrang_65134257/Views/LichChay_65134257/Index.cshtml
@model IEnumerable<QLXeBusPhuongTrang_65134257.Models.LichChay>

@{
    ViewBag.Title = "Index";
  
}

<div class="container-fluid py-4">

    <div class="d-flex justify-content-between align-items-center mb-4">
        <h2 class="text-primary fw-bold m-0">
            <i class="fas fa-calendar-alt me-2"></i> QUẢN LÝ LỊCH CHẠY
        </h2>
        <a href="@Url.Action("Create")" class="btn btn-success shadow-sm">
            <i class="fas fa-plus-circle me-1"></i> Thêm Lịch Mới
        </a>
    </div>

    <div class="mb-3">
        @if (TempData["Success"] != null)
        {
            <div class="alert alert-success alert-dismissible fade show shadow-sm" role="alert">
                <i class="fas fa-check-circle me-2"></i> @TempData["Success"]
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        }

        @if (TempData["Error"] != null)
        {
            <div class="alert alert-danger alert-dismissible fade show shadow-sm" role="alert">
                <i class="fas fa-exclamation-triangle me-2"></i> @TempData["Error"]
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        }
    </div>

    <div class="card shadow border-0 rounded-3">
        <div class="card-header bg-light py-3">
            <h6 class="m-0 font-weight-bold text-primary">Danh Sách Các Chuyến Đang Hoạt Động</h6>
        </div>

        <div class="card-body p-0">
            <div class="table-responsive">
                <table class="table table-hover table-striped align-middle mb-0">
                    <thead class="bg-primary text-white text-center">
                        <tr>
                            <th class="py-3">Tuyến Xe / Biển Số</th>
                            <th class="py-3">Tài Xế</th>
                            <th class="py-3">Thời Gian Khởi Hành</th>
                            <th class="py-3">Dự Kiến Đến</th>
                            <th class="py-3">Trạng Thái</th>
                            <th class="py-3" style="width: 150px;">Thao Tác</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    <div class="d-flex flex-column">
                                        <span class="fw-bold text-dark">
                                            <i class="fas fa-route text-danger me-1"></i> @item.Tuyen.TenTuyen
                                        </span>
                                        <small class="text-muted mt-1">
                                            <i class="fas fa-bus text-secondary me-1"></i> Xe:
                                            <span class="badge bg-light text-dark border">@item.Xe.BienSo</span>
                                        </small>
                                    </div>
                                </td>

                                <td class="text-center">
                                    <span class="fw-bold text-secondary">@item.TaiXe.HoTen</span>
                                </td>

                                <td class="text-center">
                                    <div class="fw-bold text-primary">
                                        @item.GioKhoiHanh.ToString(@"hh\:mm") <br />
                                    </div>
                                </td>

                                <td class="text-center">
                                    <div class="fw-bold text-success">
                                        @item.GioDen.ToString(@"hh\:mm")
                                    </div>
                                </td>

                                <td class="text-center">
                                    @{
                                        string statusClass = "bg-secondary";
                                        string icon = "fa-minus";

                                        if (item.TrangThai != null)
                                        {
                                            if (item.TrangThai.Contains("Đang hoạt động") || item.TrangThai.Contains("Sẵn sàng"))
                                            {
                                                statusClass = "bg-success";
                                                icon = "fa-check-circle";
                                            }
                                            else if (item.TrangThai.Contains("Tạm ngưng") || item.TrangThai.Contains("Hủy"))
                                            {
                                                statusClass = "bg-danger";
                                                icon = "fa-times-circle";
                                            }
                                            else
                                            {
                                                statusClass = "bg-warning text-dark";
                                                icon = "fa-clock";
                                            }
                                        }
                                    }
                                    <span class="badge @statusClass p-2">
                                        <i class="fas @icon me-1"></i> @item.TrangThai
                                    </span>
                                </td>

                                <td class="text-center">
                                    <div class="btn-group " role="group">
                                        <a href="@Url.Action("Edit", new { id = item.MaLichChay })" class="btn btn-warning btn-sm text-white" title="Sửa">
                                            <i class="fas fa-edit"></i>
                                        </a>
                                        @using (Html.BeginForm("Delete", "LichChay_65134257", new { id = item.MaLichChay }, FormMethod.Post, new { style = "display:inline;" }))
                                        {
                                            @Html.AntiForgeryToken()
                                            <button type="submit" class="btn btn-danger btn-sm"
                                                    title="Xóa"
                                                    onclick="return confirm('Bạn có chắc chắn muốn xóa lịch chạy này không?');">
                                                <i class="fas fa-trash-alt"></i>
                                            </button>
                                        }
                                    </div>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>

        <div class="card-footer bg-white py-3">
            <small class="text-muted">Hiển thị @Model.Count() bản ghi</small>
        </div>
    </div>
</div>

<style>
    /* CSS tùy chỉnh nhỏ để bảng đẹp hơn */
    .table thead th {
        vertical-align: middle;
        font-weight: 600;
        text-transform: uppercase;
        font-size: 0.85rem;
        letter-spacing: 0.5px;
    }

    .table tbody td {
        vertical-align: middle;
        font-size: 0.95rem;
    }

    .btn-group .btn {
        margin: 0 2px;
        border-radius: 4px !important;
    }
</style>